name: Daily Tracker Run

on:
  schedule:
    - cron: '11 8 * * *'   # runs daily at 08:11 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run
        run: python track.py
